### PR TITLE
fix: add the serviceAccountName

### PR DESCRIPTION
**Pull request by pmuir**

### CODE REVIEW

**Comment by pmuir** [comment]
/approve

I'm adding this as it fixes stuff, but may need reverting ;-)

**Comment by rawlingsj** [comment]
ok :)

**Comment by pmuir** [comment]
Haha - ok it's correct or ok it needs reverting?

**Comment by rawlingsj** [comment]
I'm not sure why but I'd been adding the ServiceAccount to the `buid_spec` in the prow config https://github.com/jenkins-x/prow-config/blob/master/prow/config.yaml#L453

Not sure which is best TBH, so if this fixes stuff keep this.

Want me to upgrade the prod cluster as auto update isn't enabled quite yet.

**Comment by pmuir** [comment]
Weird. It's there for there for promotions but it's missing for apps - see https://github.com/jenkins-x/jx/blob/master/pkg/prow/prow.go#L164

**Pull request merged**
